#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app_ticket_add:
    path: /ticket/add
    controller: App\Controller\TicketController::add

app_ticket_all:
    path: /ticket/all
    controller: App\Controller\TicketController::ticket
    
app_ticket_log:
    path: /public
    controller: App\Controller\ConnexionController::register
    
app_ticket_co:
    path: /login
    controller: App\Controller\ConnexionController::login
    
app_ticket_acc:
    path: /acceuil
    controller: App\Controller\TicketController::acceuil
    
app_ticket_mesTickets:
    path: /ticket/me
    controller: App\Controller\TicketController::mesTickets
    
app_ticket_stats:
    path: /ticket/stats
    controller: App\Controller\TicketController::stats
